package com.example.dotaapp;


public interface HeroImages 
{
			
	public String[] heroName ={
			"Abaddon",
			"Alchemist",
			"Ancient Apparition",
			"Anti Mage",
			"Axe",
			"Bane",
			"Batrider",
			"Beastmaster",
			"Bloodseeker",
			"Bounty Hunter",
			"Brewmaster",
			"Bristleback",
			"Broodmother",
			"Centuar Warrunner",
			"Chaos Knight",
			"Chen",
			"Clinkz",
			"Crystal Maiden",
			"Dark Seer",
			"Dazzle",
			"Death Prophet",
			"Disruptor",
			"Doom",
			"Dragon Knight",
			"Drow Ranger",
			"Earthshaker",
			"Elder Titan",
			"Enchantress",
			"Enigma",
			"Faceless Void",
			"Furion",
			"Gyrocopter",
			"Huskar",
			"Invoker",
			"Jakiro",
			"Juggernaut",
			"Keeper of the Light",
			"Kunkka",
			"Leshrac",
			"Lich",
			"Lifestealer",
			"Lina",
			"Lion",
			"Lone Druid",
			"Luna",
			"Lycan",
			"Magnus",
			"Medusa",
			"Meepo",
			"Mirana",	
			"Morphling",
			"Naga Siren",
			"Necrophos",
			"Nevermore",
			"Night Stalker",
			"Nyx Assassin",
			"Outworld Destroyer",
			"Ogre Magi",
			"Omniknight",
			"Phantom Assassin",
			"Phantom Lancer",
			"Puck",
			"Pudge",
			"Pugna",
			"Queen of Pain",
			"Rattletrap",
			"Razor",
			"Riki",
			"Rubick",
			"Sand King",
			"Shadow Demon",
			"Shadow Shaman",
			"Shredder",
			"Silencer",
			"Wraith King",
			"Skywrath Mage",
			"Slardar",
			"Slark",
			"Sniper",
			"Spectre",
			"Spirit Breaker",
			"Storm Spirit",
			"Sven",
			"Templar Assassin",
			"Tidehunter",
			"Tinker",	
			"Tiny",
			"Treant Protector",
			"Troll Warlord",
			"Tusk",
			"Undying",
			"Ursa",
			"Vengeful Spirit",
			"Venomancer",
			"Viper",
			"Visage",
			"Warlock",
			"Weaver",
			"Windranger",
			"Wisp",
			"Witch Doctor",
			"Zeus"};
	
    public Integer[] heroImage = { 
    		R.drawable.abaddon_full,
    		R.drawable.alchemist_full, 
    		R.drawable.ancient_apparition_full, 
    		R.drawable.antimage_full, 
    		R.drawable.axe_full, 
    		R.drawable.bane_full, 
    		R.drawable.batrider_full, 
    		R.drawable.beastmaster_full, 
    		R.drawable.bloodseeker_full, 
    		R.drawable.bounty_hunter_full, 
    		R.drawable.brewmaster_full, 
    		R.drawable.bristleback_full, 
    		R.drawable.broodmother_full, 
    		R.drawable.centaur_full, 
    		R.drawable.chaos_knight_full, 
    		R.drawable.chen_full, 
    		R.drawable.clinkz_full, 
    		R.drawable.crystal_maiden_full, 
    		R.drawable.dark_seer_full, 
    		R.drawable.dazzle_full, 
    		R.drawable.death_prophet_full, 
    		R.drawable.disruptor_full,
    		R.drawable.doom_bringer_full, 
    		R.drawable.dragon_knight_full, 
    		R.drawable.drow_ranger_full, 
    		R.drawable.earthshaker_full, 
    		R.drawable.elder_titan_full, 
    		R.drawable.enchantress_full, 
    		R.drawable.enigma_full, 
    		R.drawable.faceless_void_full, 
    		R.drawable.furion_full, 
    		R.drawable.gyrocopter_full, 
    		R.drawable.huskar_full, 
    		R.drawable.invoker_full, 
    		R.drawable.jakiro_full, 
    		R.drawable.juggernaut_full, 
    		R.drawable.keeper_of_the_light_full, 
    		R.drawable.kunkka_full, 
    		R.drawable.leshrac_full, 
    		R.drawable.lich_full, 
    		R.drawable.life_stealer_full, 
    		R.drawable.lina_full, 
    		R.drawable.lion_full, 
    		R.drawable.lone_druid_full,
    		R.drawable.luna_full, 
    		R.drawable.lycan_full, 
    		R.drawable.magnataur_full, 
    		R.drawable.medusa_full,
    		R.drawable.meepo_full,
    		R.drawable.mirana_full,    		
    		R.drawable.morphling_full, 
    		R.drawable.naga_siren_full, 
    		R.drawable.necrolyte_full, 
    		R.drawable.nevermore_full, 
    		R.drawable.night_stalker_full, 
    		R.drawable.nyx_assassin_full, 
    		R.drawable.obsidian_destroyer_full, 
    		R.drawable.ogre_magi_full, 
    		R.drawable.omniknight_full, 
    		R.drawable.phantom_assassin_full, 
    		R.drawable.phantom_lancer_full, 
    		R.drawable.puck_full, 
    		R.drawable.pudge_full, 
    		R.drawable.pugna_full, 
    		R.drawable.queenofpain_full, 
    		R.drawable.rattletrap_full, 
    		R.drawable.razor_full,
    		R.drawable.riki_full, 
    		R.drawable.rubick_full, 
    		R.drawable.sand_king_full, 
    		R.drawable.shadow_demon_full, 
    		R.drawable.shadow_shaman_full, 
    		R.drawable.shredder_full, 
    		R.drawable.silencer_full, 
    		R.drawable.skeleton_king_full, 
    		R.drawable.skywrath_mage_full, 
    		R.drawable.slardar_full,
    		R.drawable.slark_full, 
    		R.drawable.sniper_full, 
    		R.drawable.spectre_full, 
    		R.drawable.spirit_breaker_full, 
    		R.drawable.storm_spirit_full, 
    		R.drawable.sven_full, 
    		R.drawable.templar_assassin_full, 
    		R.drawable.tidehunter_full, 
    		R.drawable.tinker_full, 
    		R.drawable.tiny_full,
    		R.drawable.treant_full, 
    		R.drawable.troll_warlord_full, 
    		R.drawable.tusk_full, 
    		R.drawable.undying_full, 
    		R.drawable.ursa_full, 
    		R.drawable.vengefulspirit_full, 
    		R.drawable.venomancer_full, 
    		R.drawable.viper_full, 
    		R.drawable.visage_full, 
    		R.drawable.warlock_full,
    		R.drawable.weaver_full, 
    		R.drawable.windrunner_full, 
    		R.drawable.wisp_full, 
    		R.drawable.witch_doctor_full, 
    		R.drawable.zuus_full};
    
    public Integer[] heroAttribute = {

    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.strength,
    		R.drawable.strength,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.intelligence,
    		R.drawable.agility,
    		R.drawable.intelligence,
    		R.drawable.strength,
    		R.drawable.intelligence,
    		R.drawable.intelligence
    };	
	
    public String[] heroURLS = {
			"http://www.dota2.com/hero/Abaddon/",
			"http://www.dota2.com/hero/Alchemist/",
			"http://www.dota2.com/hero/Ancient_Apparition/",
			"http://www.dota2.com/hero/Anti_Mage/",
			"http://www.dota2.com/hero/Axe/",
			"http://www.dota2.com/hero/Bane/",
			"http://www.dota2.com/hero/Batrider/",
			"http://www.dota2.com/hero/Beastmaster/",
			"http://www.dota2.com/hero/Bloodseeker/",
			"http://www.dota2.com/hero/Bounty_Hunter/",
			"http://www.dota2.com/hero/Brewmaster/",
			"http://www.dota2.com/hero/Bristleback/",
			"http://www.dota2.com/hero/Broodmother/",
			"http://www.dota2.com/hero/Centuar_Warrunner/",
			"http://www.dota2.com/hero/Chaos_Knight/",
			"http://www.dota2.com/hero/Chen/",
			"http://www.dota2.com/hero/Clinkz/",
			"http://www.dota2.com/hero/Crystal_Maiden/",
			"http://www.dota2.com/hero/Dark_Seer/",
			"http://www.dota2.com/hero/Dazzle/",
			"http://www.dota2.com/hero/Death_Prophet/",
			"http://www.dota2.com/hero/Disruptor/",
			"http://www.dota2.com/hero/Doom/",
			"http://www.dota2.com/hero/Dragon_Knight/",
			"http://www.dota2.com/hero/Drow_Ranger/",
			"http://www.dota2.com/hero/Earthshaker/",
			"http://www.dota2.com/hero/Elder_Titan/",
			"http://www.dota2.com/hero/Enchantress/",
			"http://www.dota2.com/hero/Enigma/",
			"http://www.dota2.com/hero/Faceless_Void/",
			"http://www.dota2.com/hero/Natures_Prophet/",
			"http://www.dota2.com/hero/Gyrocopter/",
			"http://www.dota2.com/hero/Huskar/",
			"http://www.dota2.com/hero/Invoker/",
			"http://www.dota2.com/hero/Jakiro/",
			"http://www.dota2.com/hero/Juggernaut/",
			"http://www.dota2.com/hero/Keeper_of_the_Light/",
			"http://www.dota2.com/hero/Kunkka/",
			"http://www.dota2.com/hero/Leshrac/",
			"http://www.dota2.com/hero/Lich/",
			"http://www.dota2.com/hero/Lifestealer/",
			"http://www.dota2.com/hero/Lina/",
			"http://www.dota2.com/hero/Lion/",
			"http://www.dota2.com/hero/Lone_Druid/",
			"http://www.dota2.com/hero/Luna/",
			"http://www.dota2.com/hero/Lycan/",
			"http://www.dota2.com/hero/Magnus/",
			"http://www.dota2.com/hero/Medusa/",
			"http://www.dota2.com/hero/Meepo/",
			"http://www.dota2.com/hero/Mirana/",	
			"http://www.dota2.com/hero/Morphling/",
			"http://www.dota2.com/hero/Naga_Siren/",
			"http://www.dota2.com/hero/Necrophos/",
			"http://www.dota2.com/hero/Shadow_Fiend/",
			"http://www.dota2.com/hero/Night_Stalker",
			"http://www.dota2.com/hero/Nyx_Assassin/",
			"http://www.dota2.com/hero/Outworld_Devourer/",
			"http://www.dota2.com/hero/Ogre Magi/",
			"http://www.dota2.com/hero/Omniknight/",
			"http://www.dota2.com/hero/Phantom_Assassin/",
			"http://www.dota2.com/hero/Phantom_Lancer/",
			"http://www.dota2.com/hero/Puck/",
			"http://www.dota2.com/hero/Pudge/",
			"http://www.dota2.com/hero/Pugna/",
			"http://www.dota2.com/hero/Queen_of_Pain/",
			"http://www.dota2.com/hero/Clockwerk/",
			"http://www.dota2.com/hero/Razor/",
			"http://www.dota2.com/hero/Riki/",
			"http://www.dota2.com/hero/Rubick/",
			"http://www.dota2.com/hero/Sand_King/",
			"http://www.dota2.com/hero/Shadow_Demon/",
			"http://www.dota2.com/hero/Shadow_Shaman/",
			"http://www.dota2.com/hero/Timbersaw/",
			"http://www.dota2.com/hero/Silencer/",
			"http://www.dota2.com/hero/Wraith_King/",
			"http://www.dota2.com/hero/Skywrath_Mage/",
			"http://www.dota2.com/hero/Slardar/",
			"http://www.dota2.com/hero/Slark/",
			"http://www.dota2.com/hero/Sniper/",
			"http://www.dota2.com/hero/Spectre/",
			"http://www.dota2.com/hero/Spirit_Breaker/",
			"http://www.dota2.com/hero/Storm_Spirit/",
			"http://www.dota2.com/hero/Sven",
			"http://www.dota2.com/hero/Templar_Assassin/",
			"http://www.dota2.com/hero/Tidehunter/",
			"http://www.dota2.com/hero/Tinker/",	
			"http://www.dota2.com/hero/Tiny/",
			"http://www.dota2.com/hero/Treant_Protector/",
			"http://www.dota2.com/hero/Troll_Warlord/",
			"http://www.dota2.com/hero/Tusk/",
			"http://www.dota2.com/hero/Undying/",
			"http://www.dota2.com/hero/Ursa",
			"http://www.dota2.com/hero/Vengeful_Spirit/",
			"http://www.dota2.com/hero/Venomancer/",
			"http://www.dota2.com/hero/Viper/",
			"http://www.dota2.com/hero/Visage/",
			"http://www.dota2.com/hero/Warlock/",
			"http://www.dota2.com/hero/Weaver/",
			"http://www.dota2.com/hero/Windranger/",
			"http://www.dota2.com/hero/Io/",
			"http://www.dota2.com/hero/Witch_Doctor/",
			"http://www.dota2.com/hero/Zeus/"
    };

//	------------ABBADON------------

    
	public Integer[] abbadonBundleImages = {
			R.drawable.abaddon_full,
	    	R.drawable.mistcoil,
	    	R.drawable.aphoticshield,
	    	R.drawable.curseofavernus,
	    	R.drawable.borrowedtime,
	};
	
	public String[] abbadonAbilitiesStrings ={
			"Abaddon",
			"Mist Coil",
			"Aphotic Shield",
			"Curse of Avernus",
			"Borrowed Time",			
			};

	public Integer[] abbadonAbilityImages = {
			R.drawable.abbadonstats,
			R.drawable.mistcoildes,
			R.drawable.aphoticshielddes,
			R.drawable.curseofavernusdes,
			R.drawable.borrowedtimedes
	};

//	------------ALCHEMIST------------	
	
	public Integer[] alchemistBundleImages = {
			R.drawable.alchemist_full,
			R.drawable.acidspray,
			R.drawable.unstableconcoction,
			R.drawable.greevilsgreed,
			R.drawable.chemicalrage
	};
	
	public String[] alchemistAbilitiesStrings = {
			"Alchemist",
			"Acid Spray",
			"Unstable Concoction",
			"Greevil's Greed",
			"Chemical Rage"
	};
	
	public Integer[] alchemistAbilityImages = {
			R.drawable.alchstats,
			R.drawable.acidspraydes,
			R.drawable.unstableconcoctionded,
			R.drawable.greevilsgreeddes,
			R.drawable.chemicalragedes
	};
	
//	------------ANCIENT APPARITION------------
	
	public Integer[] aaBundleImages = {
			R.drawable.ancient_apparition_full,
			R.drawable.coldfeet,
			R.drawable.icevortex,
			R.drawable.chillingtouch,
			R.drawable.iceblast
	};
	
	public String[] aaAbilityStrings = {
			"Ancient Apparition",
			"Cold Feet",
			"Ice Vortex",
			"Chilling Touch",
			"Ice Blast"
	};
	
	public Integer[] aaAbilityImages = {
			R.drawable.aastats,
			R.drawable.coldfeetdes,
			R.drawable.icevortexdes,
			R.drawable.chillingtouchdes,
			R.drawable.iceblastdes
	};
	
//	------------ANTI MAGE------------

	public Integer[] antimageBundleImages = {
			R.drawable.antimage_full,
			R.drawable.manabreak,
			R.drawable.blink,
			R.drawable.spellshield,
			R.drawable.manavoid
	};
	
	public String[] antimageAbilityStrings = {
			"Anti Mage",
			"Mana Break",
			"Blink",
			"Spell Shield",
			"Mana Void"
	};
	
	public Integer[] antimageAbilityImages = {
			R.drawable.antimagestats,
			R.drawable.manabreakdef,
			R.drawable.blinkdef,
			R.drawable.spellshielddef,
			R.drawable.manavoiddef	
	};
	
//	------------AXE------------

	public Integer[] axeBundleImages = {
			R.drawable.axe_full,
			R.drawable.beserkerscall,
			R.drawable.battlehunger,
			R.drawable.counterhelix,
			R.drawable.cullingblade
	};
	
	public String[] axeAbilityStrings = {
			"Axe",
			"Beserker's Call",
			"Battle Hunger",
			"Counter Helix",
			"Culling Blade"
	};
	
	public Integer[] axeAbilityImages = {
			R.drawable.axestats,
			R.drawable.beserkerscalldef,
			R.drawable.battlehungerdef,
			R.drawable.counterhelixdef,
			R.drawable.cullingbladedef	
	};
	
//	------------FILL IN------------

	public Integer[] fillinBundleImages = {
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo
	};
	
	public String[] fillinAbilityStrings = {
			"Coming Soon!",
			"Coming Soon!",
			"Coming Soon!",
			"Coming Soon!",
			"Coming Soon!"
	};
	
	public Integer[] fillinAbilityImages = {
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo	
	};	
}
