package com.example.dotaapp;

public interface ItemImages 
{
	public String[] itemName = {
			"Iron Branch",
			"Clarity",
			"Tango",
			"Healing Salve",
			"Stout Shield",
			"Quelling Blade",
			"Ring of Protection",
			"Mango",
			"Bottle",
			"Magic Stick",
			"Orb of Venom",
			"Blade of Attack",
			"Poor Mans Shield",
			"Ring Of Basilius",
			"Boots of Speed",
			"Cloak",
			"Armor",
			"Null Tailsman",
			"Wraith Band",
			"Bracer",
			"Headress",
			"Buckler",
			"Urn of Shadows",
			"Void Stone",
			"Ring of Health",
			"Morbid Mask",
			"Soul Ring",
			"Helm of Iron Will",
			"Ring of Aquilla",
			"Medallion of Courage",
			"Ogre Club",
			"Blade of Alacrity",
			"Staff of Wizardry",
			"Tranquil Boots",
			"Phase Boots",
			"Power Treads",
			"Arcane Boots",
			"Broadsword",
			"Claymore",
			"Javelin",
			"Mithrill Hammer",
			"Shadow Amulet",
			"Drum of Endurance",
			"Glimmer Cape",
			"Vladimir's Offering",
			"Mekanism",
			"Hand of Midas",
			"Viel of Discord",
			"Force Staff",
			"Blink Dagger",
			"Boots of Travel",
			"Mask of Madness",
			"Helm of the Dominator",
			"Vanguard",
			"Hood of Defiance",
			"Blademail",
			"Solar Crest",
			"Yasha",
			"Sange",
			"Crystalis",
			"Shadow Blade",
			"Armlet of Morggidon",
			"Maelstrom",
			"Diffusal Blade",
			"Skull Basher",
			"Desolator",			
			"Crimson Guard",
			"Pipe of Insight",
			"Rod of Atos",
			"Lotus Orb",
			"Necronomicon",
			"Eul's Scepter of Divinity",
			"Dagon",
			"Orchid Malelovince",
			"Aghenim's Scepter",
			"Sange and Yasha",
			"Black King Bar",
			"Battlefury",
			"Heaven's Halberd",
			"Manta Style",
			"Ethereal Blade",
			"Shiva's Guard",
			"Bloodstone",
			"Assault Curiass",
			"Linken's Sphere",
			"Silver's Edge",
			"Octarine Core",
			"Heart of Terrasque",
			"Eye of Skadi",
			"Satanic",
			"Scythe of Vyse",	
			"Monkey King Bar",
			"Mjolnir",
			"Daedelus",
			"Radiance",
			"Refresher Orb",
			"Butterfly",
			"Abyssal Blade",
			"Aegis of the Immortal",
			"Divine Rapier"};
	
    public Integer[] itemImage = {

    		R.drawable.ironbranch,
    		R.drawable.clarity,
    		R.drawable.tango,
    		R.drawable.salve,
    		R.drawable.stoutshield,
    		R.drawable.quellingblade,
    		R.drawable.ringofprotection,
    		R.drawable.mango,
    		R.drawable.bottle,
    		R.drawable.magicstick,
    		R.drawable.orbofvenom,
    		R.drawable.bladeofattack,
    		R.drawable.poormansshield,
    		R.drawable.ringofbasi,
    		R.drawable.bootsofspeed,
    		R.drawable.cloak,
    		R.drawable.armor,
    		R.drawable.nulltailsman,
    		R.drawable.wraithband,
    		R.drawable.bracer,
    		R.drawable.headress,
    		R.drawable.buckler,
    		R.drawable.urnofshadows,
    		R.drawable.voidstone,
    		R.drawable.ringofhealth,
    		R.drawable.morbidmask,
    		R.drawable.soulring,
    		R.drawable.helmofironwill,
    		R.drawable.ringofaquilla,
    		R.drawable.medallion,
    		R.drawable.ogreclub,
    		R.drawable.bladeofalacrity,
    		R.drawable.staffofwizardry,
    		R.drawable.tranquilboots,
    		R.drawable.phaseboots,
    		R.drawable.powertreads,
    		R.drawable.manaboots,
    		R.drawable.broadsword,
    		R.drawable.claymore,
    		R.drawable.javelin,
    		R.drawable.mithrilhammer,
    		R.drawable.shadowamulet,
    		R.drawable.drums,
    		R.drawable.glimmercape,
    		R.drawable.vlads,
    		R.drawable.mekanism,
    		R.drawable.midas,
    		R.drawable.veilofdiscord,
    		R.drawable.forcestaff,
    		R.drawable.blinkdagger,
    		R.drawable.bootsoftravel,
    		R.drawable.maskofmadness,
    		R.drawable.helmofdominator,
    		R.drawable.vanguard,
    		R.drawable.hoodofdefiance,
    		R.drawable.blademail,
    		R.drawable.solarcrest,
    		R.drawable.yasha,
    		R.drawable.sange,
    		R.drawable.crystalis,
    		R.drawable.shadowblade,
    		R.drawable.armlet,
    		R.drawable.maelstrom,
    		R.drawable.diffusal,
    		R.drawable.skullbasher,
    		R.drawable.desolator,
    		R.drawable.crimsonguard,
    		R.drawable.pipeofinsight,
    		R.drawable.rodofatos,
    		R.drawable.lotusorb,
    		R.drawable.necrobook,
    		R.drawable.eulsscepter,
    		R.drawable.dagon,
    		R.drawable.orchid,
    		R.drawable.aghsscepter,
    		R.drawable.sangeandyasha,
    		R.drawable.blackkingbar,
    		R.drawable.battlefury,
    		R.drawable.heavenshalberd,
    		R.drawable.mantastyle,
    		R.drawable.eblade,
    		R.drawable.shivas,
    		R.drawable.bloodstone,
    		R.drawable.assaultcuriass,
    		R.drawable.linkenssphere,
    		R.drawable.silveredge,
    		R.drawable.octarinecore,
    		R.drawable.heartofterrasque,
    		R.drawable.eyeofskadi,
    		R.drawable.satanic,
    		R.drawable.scytheofvyse,
    		R.drawable.monkeykingbar,
    		R.drawable.mjolnir,
    		R.drawable.daedelus,
    		R.drawable.radiance,
    		R.drawable.refresherorb,
    		R.drawable.butterfly,
    		R.drawable.abyssalblade,
    		R.drawable.aegis,
    		R.drawable.divinerapier};
      
	public String[] itemCost = {
			"50g",
			"50g",
			"115g",
			"120g",
			"Stout Shield",
			"Quelling Blade",
			"Ring of Protection",
			"Mango",
			"Bottle",
			"Magic Stick",
			"Orb of Venom",
			"Blade of Attack",
			"Poor Mans Shield",
			"Ring Of Basilius",
			"Boots of Speed",
			"Cloak",
			"Armor",
			"Null Tailsman",
			"Wraith Band",
			"Bracer",
			"Headress",
			"Buckler",
			"Urn of Shadows",
			"Void Stone",
			"Ring of Health",
			"Morbid Mask",
			"Soul Ring",
			"Helm of Iron Will",
			"Ring of Aquilla",
			"Medallion of Courage",
			"Ogre Club",
			"Blade of Alacrity",
			"Staff of Wizardry",
			"Tranquil Boots",
			"Phase Boots",
			"Power Treads",
			"Arcane Boots",
			"Broadsword",
			"Claymore",
			"Javelin",
			"Mithrill Hammer",
			"Shadow Amulet",
			"Drum of Endurance",
			"Glimmer Cape",
			"Vladimir's Offering",
			"Mekanism",
			"Hand of Midas",
			"Viel of Discord",
			"Force Staff",
			"Blink Dagger",
			"Boots of Travel",
			"Mask of Madness",
			"Helm of the Dominator",
			"Vanguard",
			"Hood of Defiance",
			"Blademail",
			"Solar Crest",
			"Yasha",
			"Sange",
			"Crystalis",
			"Shadow Blade",
			"Armlet of Morggidon",
			"Maelstrom",
			"Diffusal Blade",
			"Skull Basher",
			"Desolator",			
			"Crimson Guard",
			"Pipe of Insight",
			"Rod of Atos",
			"Lotus Orb",
			"Necronomicon",
			"Eul's Scepter of Divinity",
			"Dagon",
			"Orchid Malelovince",
			"Aghenim's Scepter",
			"Sange and Yasha",
			"Black King Bar",
			"Battlefury",
			"Heaven's Halberd",
			"Manta Style",
			"Ethereal Blade",
			"Shiva's Guard",
			"Bloodstone",
			"Assault Curiass",
			"Linken's Sphere",
			"Silver's Edge",
			"Octarine Core",
			"Heart of Terrasque",
			"Eye of Skadi",
			"Satanic",
			"Scythe of Vyse",	
			"Monkey King Bar",
			"Mjolnir",
			"Daedelus",
			"Radiance",
			"Refresher Orb",
			"Butterfly",
			"Abyssal Blade",
			"Aegis of the Immortal",
			"Divine Rapier"
			};
	
	public Integer[] itemDescription = {
			R.drawable.ironbranchinfo,
			R.drawable.clarityinfo,
			R.drawable.tangoinfo,
			R.drawable.healingsalveinfo,
			R.drawable.stoutshieldinfo,
			R.drawable.quellingbladeinfo,
			R.drawable.ringofprotectioninfo,
			R.drawable.mangoinfo,
			R.drawable.bottleinfo,
			R.drawable.magicstickinfo,
			R.drawable.orbofvenominfo,
			R.drawable.bladesofattackinfo,
			R.drawable.poormansshieldinfo,
			R.drawable.ringofbasiinfo,
			R.drawable.bootsofspeedinfo,
			R.drawable.cloakinfo,
			R.drawable.armorinfo,
			R.drawable.nulltailsmaninfo,
			R.drawable.wraithbandinfo,
			R.drawable.bracerinfo,
			R.drawable.headressinfo,
			R.drawable.bucklerinfo,
			R.drawable.voidstoneinfo,
			R.drawable.ringofhealthinfo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo,
			R.drawable.dotalogo
	};
}
